defaults:
  - overrides: cartpole
  - _self_

# env cfg
env_name: ${overrides.env_name}
env_max_steps: ${overrides.env_max_steps}


train_frames_per_task: ${overrides.train_frames_per_task}
frames_per_batch: 800
init_frames_per_task: 5000
#init_frames_per_task: 0
policy_learning_frames_per_task: 0
#policy_learning_frames_per_task: 10_000

batch_size: 50
batch_length: 25
train_agent_frames: 0

optim_steps_per_batch: 80
#optim_steps_per_batch: 200
buffer_size: 20000

world_model_lr: 6e-4
actor_value_lr: 8e-5
context_lr: 1e-1
observed_logits_lr: 0.05
context_logits_lr: 0.002

# logger
record_video: 0
record_interval: 1
eval_repeat_times: 5
exp_name: default
logger: wandb
offline_logging: False

# model learning
model_type: plain
variable_num: 10
state_dim_per_variable: 3
belief_dim_per_variable: 20
disable_belief: False
free_nats: 3.0
sparse_weight: 0.0001
context_sparse_weight: 0.01
context_max_weight: 0.2
sampling_times: 30
residual: True
hidden_size: 400

# actor
actor_dist_type: tanh_normal

# meta
meta: False
max_context_dim: 10
task_num: 50


lambda_kl: 1.0
lambda_reco: 1.0
lambda_reward: 10.0
lambda_continue: 10.0
imagination_horizon: 15
discount_loss: True
pred_continue: True

train_mask_iters: 10
train_model_iters: 40


grad_clip: 100

normalize_rewards_online: False


# other
model_device: cuda:0
collector_device: cpu
seed: 42

hydra:
  run:
    dir: ./outputs/dreamer/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
