defaults:
  - overrides: cartpole

# env cfg
env_name: ${overrides.env_name}
termination_fns: ${overrides.termination_fns}
reward_fns: ${overrides.reward_fns}

# learning
train_frames_per_task: ${overrides.train_frames_per_task}
init_frames_per_task: ${overrides.init_frames_per_task}

# save
save_model_frames_per_task: 1000

# planning
planning_horizon: 15
optim_steps: 5
num_candidates: 350
top_k: 35

# model learning
model_type: causal
reinforce: True
batch_size: 256
buffer_size: 10000
model_learning_per_frame: 5
train_mask_iters: 10
train_model_iters: 40
world_model_lr: 0.001
context_lr: 0.001
observed_logits_lr: 0.002
context_logits_lr: 0.002
world_model_weight_decay: 0.001
hidden_size: 256
hidden_layers: 2

lambda_transition: 1.0
lambda_reward: 10.0
lambda_terminated: 10.0
lambda_mutual_info: 0.0

sparse_weight: 0.05
context_sparse_weight: 0.02
context_max_weight: 0.1
sampling_times: 30

# log
exp_name: default
logger: tensorboard
offline_logging: False
eval_interval_frames_per_task: ${overrides.eval_interval_frames_per_task}
eval_repeat_nums: 3

# meta-RL
meta: True
max_context_dim: 10
task_num: 50
meta_test_task_num: 20
meta_test_interval_frames_per_task: ${overrides.meta_test_interval_frames_per_task}
meta_task_adjust_frames_per_task: 50
meta_test_model_learning_per_frame: 5
oracle_context: ${overrides.oracle_context}
new_oracle_context: ${overrides.new_oracle_context}

# other
device: cuda:1