# env cfg
env_name: CartPoleContinuous-v0
cancel_mujoco_frame_skip: True # work when env is mujoco env
termination_fns: ""
reward_fns: ""

# planning
total_frames: 300000
init_random_frames: 3000
frames_per_batch: 1
planning_horizon: 15
optim_steps: 5
num_candidates: 350
top_k: 35

# model learning
model_type: causal
reinforce: True
batch_size: 256
model_learning_per_step: 10
train_mask_iters: 10
train_model_iters: 50
world_model_lr: 0.001
context_lr: 0.001
observed_logits_lr: 0.002
context_logits_lr: 0.002
hidden_size: 256
hidden_layers: 2

lambda_transition: 1.0
lambda_reward: 1.0
lambda_terminated: 20.0
lambda_mutual_info: 0.0

sparse_weight: 0.05
context_sparse_weight: 0.02
context_max_weight: 0.05
sampling_times: 30

# log
exp_name: default
logger: "tensorboard"
offline_logging: False
record_interval: 10
test_interval: 100
test_env_nums: 1

# meta-RL
meta: True
max_context_dim: 10
task_num: 50
oracle_context:
  #  gravity: [ 5.0, 20.0 ]
  #  masscart: [ 0.5, 4.5 ]
  #  tau: [ 0.02, 0.2 ]
  x_dot_bias: [ -0.0, 0.0 ]
#  theta_dot_bias: [ -2.0, 2.0 ]
#  theta_threshold_degree: [ 10.0, 20.0 ]

# other
device: cuda:1