env_name: MyCartPole-v0
termination_fns: "cartpole"
reward_fns: ""
env_max_steps: 200

meta: True

meta_train_frames: 500_000
meta_train_init_frames: 10_000
meta_test_frames: 10_000
frames_per_batch: 500

batch_size: 200
batch_length: 1
optim_steps_per_batch: 500

planning_horizon: 10

sparse_weight: 0.05
context_sparse_weight: 0.01
context_max_weight: 0.05

oracle_context:
  cart_vel_bias: [ -0.5, 0.5 ]
  pole_vel_bias: [ -0.5, 0.5 ]
new_oracle_context:
  gravity: [ 5.0, 20.0 ]
