env_name: MyCartPole-v0
termination_fns: "cartpole"
reward_fns: ""
env_max_steps: 200

meta: True

meta_train_frames: 500_000
meta_train_init_frames: 10_000
meta_test_frames: 4_000
frames_per_batch: 500

batch_size: 200
batch_length: 1
optim_steps_per_batch: 500

planning_horizon: 20

sparse_weight: 0.02
context_sparse_weight: 0.01
context_max_weight: 0.02

oracle_context:
  cart_vel_bias: [ -1., 1. ]
  pole_vel_bias: [ -1., 1. ]
  masscart: [ 0.8, 1.2 ]
new_oracle_context:
