env_name: MyHalfCheetah-v0
termination_fns: "no_termination"
reward_fns: ""
env_max_steps: 1000

meta: True

meta_train_frames: 1_000_000
meta_train_init_frames: 10_000
meta_test_frames: 10_000
frames_per_batch: 500
#eval_interval: 20
eval_interval: 20000

batch_size: 200
batch_length: 1
optim_steps_per_batch: 500

# planning
planning_horizon: 50
optim_steps: 5
num_candidates: 350
top_k: 35

sparse_weight: 0.02
context_sparse_weight: 0.02
context_max_weight: 0.05

oracle_context:
  torso_x_vel_bias: [ -0.5, 0.5 ]
  torso_z_vel_bias: [ -2.0, 2.0 ]
  torso_angle_vel_bias: [ -2.0, 2.0 ]
new_oracle_context:
#  goal_velocity: [ 0.5, 2.0 ]
