env_name: MultiNode53-v0
termination_fns: "no_termination"
reward_fns: ""
env_max_steps: 200

meta: False

meta_train_frames: 500_000
meta_train_init_frames: 1_000
meta_test_frames:
frames_per_batch: 50

batch_size: 200
batch_length: 1
optim_steps_per_batch: 100

planning_horizon: 10

sparse_weight: 0.02
context_sparse_weight: 0.
context_max_weight: 0.

oracle_context:
new_oracle_context:
