# env cfg
env_name: CartPoleContinuous-v0
cancel_mujoco_frame_skip: True # work when env is mujoco env
termination_fns: cartpole
reward_fns: ones

# planning
total_frames: 10000
init_random_frames: 1000
frames_per_batch: 1
cem_cfg:
  planning_horizon: 15
  optim_steps: 5
  num_candidates: 350
  top_k: 35

# model learning
batch_size: 256
model_learning_per_step: 10
train_mask_iters: 10
train_predictor_iters: 50
world_model_lr: 0.001
mask_logits_lr: 0.05
lambda_transition: 1.0
lambda_reward: 1.0
lambda_terminated: 1.0
sparse_weight: 0.05
context_weight: 0.1
sampling_times: 50

# log
exp_name: default
logger: wandb
offline_logging: False
record_interval: 10
test_interval: 100
test_env_nums: 5

# meta-RL
max_context_dim: 0

# other
model_device: cpu