env_name: MyCartPole-v0
termination_fns: "cartpole"
reward_fns: ""
env_max_steps: 200

meta: False

meta_train_frames: 20_000
meta_train_init_frames: 1_000
meta_test_frames:
frames_per_batch: 50

normalize_rewards_online: False

batch_size: 200
batch_length: 1
optim_steps_per_batch: 100

imagination_horizon: 1

sparse_weight: 0.05
context_sparse_weight: 0.
context_max_weight: 0.

oracle_context:
new_oracle_context: