env_name: MyCartPoleSwingUp-v0
termination_fns: "cartpole_swingup"
reward_fns: "cartpole_swingup"
env_max_steps: 200

meta: True

meta_train_frames: 500_000
meta_train_init_frames: 5_000
meta_train_logits_frames: 5_000
meta_test_frames: 4_000
frames_per_batch: 500
eval_interval: 20

normalize_rewards_online: False

batch_size: 200
batch_length: 1
model_optim_steps_per_batch: 500
policy_optim_steps_per_batch: 500

imagination_horizon: 1

sparse_weight: 0.02
context_sparse_weight: 0.01
context_max_weight: 0.1

oracle_context:
  cart_vel_bias: [ -1., 1. ]
  pole_vel_bias: [ -1., 1. ]
  masscart: [ 0.8, 1.2 ]
new_oracle_context:
